# Generated by Django 6.0.6 on 2026-07-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents_contrats/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeDeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('notes_document', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_espace', models.CharField(blank=True, max_length=100)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cycle_facturation', models.CharField(blank=True, choices=[('avance', "A l'avance"), ('debut_mois', 'Début du mois')], max_length=20)),
                ('renouvellement_automatique', models.BooleanField(default=False)),
                ('periode_facturation_personnalisee', models.BooleanField(default=False)),
                ('date_debut_facturation', models.DateField(blank=True, null=True)),
                ('date_fin_facturation', models.DateField(blank=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='groupes_contrat', to='contrats.document')),
            ],
        ),
    ]
