# Generated by Django 6.0.6 on 2026-07-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('structure_tarifaire', models.CharField(choices=[('journaliere', 'Journalière'), ('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle')], max_length=20)),
                ('tarif_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='groupedecontrat',
            name='grille_tarifaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_contrat', to='contrats.grilletarifaire'),
        ),
    ]
