# Generated by Django 6.0.6 on 2026-07-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_grilletarifaire_groupedecontrat_grille_tarifaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupedecontrat',
            name='structure_tarifaire',
            field=models.CharField(blank=True, choices=[('journaliere', 'Journalière'), ('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle')], max_length=20),
        ),
        migrations.CreateModel(
            name='FraisRemiseGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('frais', 'Frais'), ('remise', 'Remise'), ('eau_electricite', 'Eau et Electricité')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_remises', to='contrats.groupedecontrat')),
            ],
        ),
    ]
