# Generated by Django 6.0.6 on 2026-07-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur'), ('client', 'Client')], default='gestionnaire', max_length=20),
        ),
    ]
