# Generated by Django 6.0.6 on 2026-07-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeDePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_bassin', models.CharField(blank=True, max_length=100)),
                ('type_inventaire', models.CharField(blank=True, max_length=100)),
                ('total_inventaire', models.IntegerField(blank=True, null=True)),
                ('longueur_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('longueur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('largeur_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('largeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tirant_eau_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tirant_eau_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type_place', models.CharField(blank=True, max_length=100)),
                ('groupe_de_places', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='quais.groupedeplaces')),
            ],
        ),
    ]
