# Generated by Django 6.0.6 on 2026-07-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quais', '0001_initial'),
        ('reservations', '0002_articlecharge_charge_remise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('aucun', 'Ni présent ni absent')], default='aucun', max_length=10)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='quais.place')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='reservations.reservation')),
            ],
            options={
                'unique_together': {('place', 'date')},
            },
        ),
    ]
