# Generated by Django 6.0.6 on 2026-07-28 17:28

import django.db.models.deletion
import portail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_compte'),
        ('reservations', '0007_reservation_type_bassin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('permis_navigation', 'Permis de navigation'), ('assurance', 'Assurance bateau'), ('piece_identite', "Pièce d'identité"), ('autre', 'Autre')], default='autre', max_length=30)),
                ('fichier', models.FileField(upload_to=portail.models.upload_path_document_client)),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_client', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('impayee', 'Impayée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='impayee', max_length=15)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_stripe', to='portail.facture')),
            ],
        ),
    ]
