# Generated by Django 6.0.6 on 2026-07-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bateaux', '0001_initial'),
        ('clients', '0001_initial'),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateTimeField()),
                ('date_depart', models.DateTimeField()),
                ('longueur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('largeur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('en_cours', 'En cours'), ('a_facturer', 'A facturer'), ('facturee', 'Facturée')], default='confirmee', max_length=20)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('bateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bateaux.bateau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Escale',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
                ('requete_speciale', models.TextField(blank=True)),
                ('electricite_eau', models.CharField(blank=True, choices=[('eau', 'Eau'), ('electricite', 'Electricité'), ('eau_electricite', 'Eau et Electricité'), ('aucun', 'Aucun')], max_length=20)),
                ('methode_paiement', models.CharField(blank=True, choices=[('carte', 'Carte bancaire'), ('espece', 'Espèce'), ('virement', 'Virement'), ('cheque', 'Chèque')], max_length=20)),
            ],
            bases=('reservations.reservation',),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
                ('statut_signature', models.CharField(choices=[('a_envoyer', 'A envoyer'), ('envoye', 'Envoyé'), ('signe', 'Signé'), ('archive', 'Archivé'), ('resilie', 'Résilié')], default='a_envoyer', max_length=20)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('groupe_contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='contrats.groupedecontrat')),
            ],
            bases=('reservations.reservation',),
        ),
    ]
