# Generated by Django 6.0.6 on 2026-07-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('electricite', 'Electricité'), ('provisions', 'Provisions'), ('services', 'Services'), ('autres', 'Autres')], max_length=20)),
                ('taxe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.articlecharge')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliquee_mise_a_quai', models.BooleanField(default=False)),
                ('appliquee_electricite', models.BooleanField(default=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(choices=[('devise', 'Devise'), ('pourcentage', 'Pourcentage')], max_length=15)),
                ('jours_gratuits', models.PositiveIntegerField(blank=True, null=True)),
                ('raison', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='reservations.reservation')),
            ],
        ),
    ]
