# Generated by Django 6.0.6 on 2026-07-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('reservations', '0002_articlecharge_charge_remise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_bateau', models.CharField(blank=True, max_length=100)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('requete_speciale', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liste_attente', to='clients.client')),
            ],
        ),
    ]
