# Generated by Django 6.0.6 on 2026-07-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_listeattente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('a_regler', 'A régler'), ('regle', 'Réglé'), ('rembourse', 'Remboursé')], default='a_regler', max_length=15)),
                ('date_echeance', models.DateField()),
                ('date_traitement', models.DateField(blank=True, null=True)),
                ('methode', models.CharField(blank=True, choices=[('carte', 'Carte bancaire'), ('espece', 'Espèce'), ('virement', 'Virement'), ('cheque', 'Chèque')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.reservation')),
            ],
        ),
    ]
