# Generated by Django 6.0.6 on 2026-07-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_grilletarifaire_groupedecontrat_grille_tarifaire'),
        ('reservations', '0004_paiementprogramme'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='grille_tarifaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='contrats.grilletarifaire'),
        ),
    ]
