# Generated by Django 6.0.6 on 2026-07-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_grille_tarifaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
