# Generated by Django 6.0.6 on 2026-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_charge_montant_alter_charge_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type_bassin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
