# Generated by Django 6.0.6 on 2026-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('physique', 'Personne physique'), ('morale', 'Personne morale')], max_length=10)),
                ('nom_prenom', models.CharField(blank=True, max_length=255)),
                ('numero_passeport_cin', models.CharField(blank=True, max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('raison_sociale', models.CharField(blank=True, max_length=255)),
                ('registre_commerce', models.CharField(blank=True, max_length=50)),
                ('siege_social', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
