# Generated by Django 6.0.6 on 2026-07-03 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_navire', models.CharField(max_length=255)),
                ('type_bateau', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('port_attache', models.CharField(blank=True, max_length=100)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tirant_eau', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('numero_immatriculation', models.CharField(blank=True, max_length=50)),
                ('pavillon', models.CharField(blank=True, max_length=100)),
                ('assurance', models.CharField(blank=True, max_length=255)),
                ('numero_police', models.CharField(blank=True, max_length=100)),
                ('echeance_assurance', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bateaux', to='clients.client')),
            ],
        ),
    ]
